// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A portfolio customization AI agent.
 *
 * - customizePortfolio - A function that handles the portfolio customization process.
 * - CustomizePortfolioInput - The input type for the customizePortfolio function.
 * - CustomizePortfolioOutput - The return type for the customizePortfolio function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CustomizePortfolioInputSchema = z.object({
  recruiterRole: z.string().describe('The role of the recruiter viewing the portfolio.'),
  aboutMe: z.string().describe('The about me section of the portfolio.'),
  skills: z.string().describe('The skills section of the portfolio.'),
  experience: z.string().describe('The experience section of the portfolio.'),
  projects: z.string().describe('The projects section of the portfolio.'),
  education: z.string().describe('The education section of the portfolio.'),
  hobbies: z.string().describe('The hobbies section of the portfolio.'),
});
export type CustomizePortfolioInput = z.infer<typeof CustomizePortfolioInputSchema>;

const CustomizePortfolioOutputSchema = z.object({
  customizedSections: z.array(z.string()).describe('The ordered list of sections to display, based on the recruiter role.'),
  customizedAboutMe: z.string().describe('The customized about me section.'),
  customizedSkills: z.string().describe('The customized skills section.'),
  customizedExperience: z.string().describe('The customized experience section.'),
  customizedProjects: z.string().describe('The customized projects section.'),
  customizedEducation: z.string().describe('The customized education section.'),
  customizedHobbies: z.string().describe('The customized hobbies section.'),
});
export type CustomizePortfolioOutput = z.infer<typeof CustomizePortfolioOutputSchema>;

export async function customizePortfolio(input: CustomizePortfolioInput): Promise<CustomizePortfolioOutput> {
  return customizePortfolioFlow(input);
}

const prompt = ai.definePrompt({
  name: 'customizePortfolioPrompt',
  input: {schema: CustomizePortfolioInputSchema},
  output: {schema: CustomizePortfolioOutputSchema},
  prompt: `You are an expert career coach specializing in portfolio optimization. You will be given the recruiter's role and the content of the portfolio sections. You will re-order the sections based on what is most important to the recruiter, and re-write each section to highlight the most relevant information for the recruiter.

Recruiter Role: {{{recruiterRole}}}

About Me: {{{aboutMe}}}
Skills: {{{skills}}}
Experience: {{{experience}}}
Projects: {{{projects}}}
Education: {{{education}}}
Hobbies: {{{hobbies}}}

Instructions: Re-order the sections and re-write each section to be more appealing to the recruiter. The customizedSections output should be an ordered list of section names (e.g. ["Experience", "Projects", "Skills", "About Me", "Education", "Hobbies"]). The customized section fields should contain the re-written content for each section.

Output:`, 
});

const customizePortfolioFlow = ai.defineFlow(
  {
    name: 'customizePortfolioFlow',
    inputSchema: CustomizePortfolioInputSchema,
    outputSchema: CustomizePortfolioOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
